name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}        
    - name: Build the Docker image
      run:
        docker build . --file Dockerfile --tag jac18281828/${{github.event.repository.name}}:$(date +%m%d%y)-${GITHUB_SHA::10}
    - name: Push the image (release)
      run: |
        docker tag jac18281828/${{github.event.repository.name}}:$(date +%m%d%y)-${GITHUB_SHA::10} jac18281828/${{github.event.repository.name}}:latest
        docker push jac18281828/${{github.event.repository.name}}
      if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
